# Generated by Django 4.2.5 on 2023-09-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrank',
            name='sleeper_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
