# Generated by Django 4.2.5 on 2023-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_playerrank_sleeper_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('email_address', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
